http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  profile:
    host: localhost
    paths: 
     - '/api/v1/profiles'
     - '/api/v1/profiles/:id'
  auth:
    host: localhost
    paths: '/api/v1/auth*'
  todo:
    host: localhost
    paths: '/api/v1/todos*'
serviceEndpoints:
  profile_service:
    url: 'http://localhost:3000/'
  auth_service:
    url: 'http://localhost:3000/'
  todo_service:
    url: 'http://localhost:3000/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  profile_pipe:
    apiEndpoints:
      - profile
    policies:
      - proxy:
          - action:
              serviceEndpoint: profile_service
              changeOrigin: true
  auth_pipe:
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: auth_service
              changeOrigin: true
  todo_pipe:
    apiEndpoints:
      - todo
    policies:
      - proxy:
          - action:
              serviceEndpoint: todo_service
              changeOrigin: true
