http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  profile:
    host: localhost
    paths: '/profile'
  auth:
    host: localhost
    paths: '/auth'
  todo:
    host: localhost
    paths: '/todo'
serviceEndpoints:
  profile_service:
    url: 'http://localhost:3000'
  auth_service:
    url: 'http://localhost:3000'
  todo_service:
    url: 'http://localhost:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  profile_pipe:
    apiEndpoints:
      - profile
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: profile_service
              changeOrigin: true
  auth_pipe:
    apiEndpoints:
      - auth
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: auth_service
              changeOrigin: true
  todo_pipe:
    apiEndpoints:
      - todo
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: todo_service
              changeOrigin: true
