# Core
db:
  redis:
    emulate: true
    namespace: EG 

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000

plugins:
  rewrite:
    package: express-gateway-plugin-rewrite
  express-gateway-keycloak:
    package: express-gateway-keycloak
    keycloakConfig:
      realm: "todo-auth"
      auth-server-url: "https://0f1e94dc-2f46-44c5-8aba-b4cc2da9bfb5.ma.bw-cloud-instance.org/api/v1/auth/"
      ssl-required: external
      bearer-only: true
      confidential-port: 0
      resource: "todo-api" 