# Core
db:
  redis:
    emulate: true
    namespace: EG

#plugins:
  # express-gateway-plugin-example:
  #   param1: 'param from system.config'

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000

plugins:
  rewrite:
    package: express-gateway-plugin-rewrite
  express-gateway-keycloak:
    package: express-gateway-keycloak
    keycloakConfig:
      realm: "quickstart"
      auth-server-url: "https://9bedecec-b4fa-4c99-920a-ad988c144210.ma.bw-cloud-instance.org:8443/auth"
      ssl-required: external
      bearer-only: true
      confidential-port: 0
      resource: "service-nodejs" 